[package]
name = "weechat-discord"
version = "0.2.0"
authors = ["Noskcaj <kcajdev@gmail.com>"]
edition = "2018"

[lib]
name = "weecord"
crate-type = ["dylib"]

[features]
default = ["onig"]
images = ["image", "termimage"]

pcre = ["parsing/pcre"]
onig = ["parsing/onig"]

[dependencies]
libc = "0.2.60"
parking_lot = "0.9.0"
lazy_static = "1.3.0"
dirs = "2.0.1"
crossbeam-channel = "0.3.9"
json = "0.11.14"
regex = "1.2.1"
image = { version = "0.22.1", optional = true }

[dependencies.termimage]
package = "libtermimg"
optional = true
git = "https://github.com/terminal-discord/libtermimg"
rev = "271e030"

[dependencies.serenity]
git = "https://github.com/terminal-discord/serenity"
branch = "current"
default_features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "utils",
    "rustls_backend",
]

[dependencies.parsing]
path = "parsing"

[dependencies.weechat]
# path = "../rust-weechat/weechat-rs"
git = "https://github.com/terminal-discord/rust-weechat"
rev = "29f6c23"

[dependencies.weechat-sys]
# path = "../rust-weechat/weechat-sys"
git = "https://github.com/terminal-discord/rust-weechat"
rev = "29f6c23"
